/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Aug 07 15:09:21 2017. */

#include "unionproto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t msgFiredBullet_fields[3] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, msgFiredBullet, X, X, 0),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, msgFiredBullet, Y, X, 0),
	PB_LAST_FIELD
};

const pb_field_t BulletInfo_fields[3] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, BulletInfo, X, X, 0),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, BulletInfo, Y, X, 0),
	PB_LAST_FIELD
};

const pb_field_t PlayerInfo_fields[5] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, PlayerInfo, X, X, 0),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, PlayerInfo, Y, X, 0),
	PB_FIELD(3, STRING  , REQUIRED, STATIC  , OTHER, PlayerInfo, Name, Y, 0),
	PB_FIELD(4, MESSAGE , REPEATED, CALLBACK, OTHER, PlayerInfo, bullets, Name, &BulletInfo_fields),
	PB_LAST_FIELD
};

const pb_field_t msgGameData_fields[3] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, msgGameData, GameMode, GameMode, 0),
	PB_FIELD(2, MESSAGE , REPEATED, CALLBACK, OTHER, msgGameData, players, GameMode, &PlayerInfo_fields),
	PB_LAST_FIELD
};

const pb_field_t UnionMessage_fields[3] = {
	PB_FIELD(1, MESSAGE , OPTIONAL, STATIC  , FIRST, UnionMessage, msgFiredBullet, msgFiredBullet, &msgFiredBullet_fields),
	PB_FIELD(2, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, lastGameData, msgFiredBullet, &msgGameData_fields),
	PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
* compile-time option. You can do that in pb.h or on compiler command line.
*
* The reason you need to do this is that some of your messages contain tag
* numbers or field sizes that are larger than what can fit in 8 or 16 bit
* field descriptors.
*/
PB_STATIC_ASSERT((pb_membersize(UnionMessage, msgFiredBullet) < 65536 && pb_membersize(UnionMessage, lastGameData) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_msgFiredBullet_BulletInfo_PlayerInfo_msgGameData_UnionMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
	/* If you get an error here, it means that you need to define PB_FIELD_16BIT
	* compile-time option. You can do that in pb.h or on compiler command line.
	*
	* The reason you need to do this is that some of your messages contain tag
	* numbers or field sizes that are larger than what can fit in the default
	* 8 bit descriptors.
	*/
	PB_STATIC_ASSERT((pb_membersize(UnionMessage, msgFiredBullet) < 256 && pb_membersize(UnionMessage, lastGameData) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_msgFiredBullet_BulletInfo_PlayerInfo_msgGameData_UnionMessage)
#endif


	/* @@protoc_insertion_point(eof) */
